### ISSUE TITLE
Transform coordinates of "N38" files

### ISSUE THREAD

**Issue by AlbertoTabla** [obrl-soil/em38#2]
Hi!

I have problems with a ".N38" file. 
The file coordinates start as "**@$GNRMC**" and when I use "em38_from_file" I get the error "**Error in FUN (X [[i]], ...): 'list' object cannot be coerced to type 'integer'** ". How can I modify the coordinates with "**process_gprmc**"?? 

Thank you!

**Comment by obrl-soil** [comment]
Hi - yes, I've only developed for plain-jane GPS thus far since I don't have access to any *.N38 files that use other systems. I've coded a quick fix that should theoretically work; try reinstalling the package and re-running the extract, let me know how it goes.

If you're willing, it would be very helpful if you could share one of your N38 files with me so I can make sure I'm not missing anything.
